# Generated by Django 4.2.3 on 2023-08-02 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Countries_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("capital", models.CharField(max_length=100)),
                ("area", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HousePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longitude", models.IntegerField()),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=10)),
                ("housing_median", models.IntegerField()),
                ("total_rooms", models.IntegerField()),
                ("total_bedrooms", models.IntegerField()),
                ("population", models.IntegerField()),
                ("households", models.IntegerField()),
                ("median_income", models.DecimalField(decimal_places=5, max_digits=10)),
                ("ocean_proximity", models.CharField(max_length=100)),
                ("median_house_value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Country_Coorinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.countries_info",
                    ),
                ),
            ],
        ),
    ]
