# Generated by Django 4.2.4 on 2023-08-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dbf_file", models.FileField(upload_to="Shapes_Files")),
                ("shp_file", models.FileField(upload_to="Shapes_Files")),
                ("shx_file", models.FileField(upload_to="Shapes_Files")),
                ("database_name", models.CharField(max_length=500)),
            ],
        ),
    ]
