# Generated by Django 4.2.3 on 2023-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Countries_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("capital", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=10)),
                ("area", models.IntegerField()),
            ],
        ),
    ]
