# Generated by Django 4.2.4 on 2023-08-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_uploadfiledata_dbf_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfiledata",
            name="dbf_file",
            field=models.FileField(upload_to="Spatial_Files11072"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shp_file",
            field=models.FileField(upload_to="Spatial_Files11072"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shx_file",
            field=models.FileField(upload_to="Spatial_Files11072"),
        ),
    ]
