# Generated by Django 4.2.4 on 2023-08-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_uploadfiledata_dbf_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NycData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BLKID", models.CharField(max_length=50)),
                ("POPN_TOTAL", models.IntegerField()),
                ("POPN_WHITE", models.IntegerField()),
                ("POPN_BLACK", models.IntegerField()),
                ("POPN_NATIV", models.IntegerField()),
                ("POPN_ASIAN", models.IntegerField()),
                ("POPN_OTHER", models.IntegerField()),
                ("BORONAME", models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="dbf_file",
            field=models.FileField(upload_to="Spatial_Files89017"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shp_file",
            field=models.FileField(upload_to="Spatial_Files89017"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shx_file",
            field=models.FileField(upload_to="Spatial_Files89017"),
        ),
        migrations.CreateModel(
            name="Nyc_Coordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_coord", models.DecimalField(decimal_places=10, max_digits=10)),
                ("y_coord", models.DecimalField(decimal_places=10, max_digits=10)),
                (
                    "nyc_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.nycdata"
                    ),
                ),
            ],
        ),
    ]
