# Generated by Django 4.2.4 on 2023-08-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_nycdata_alter_uploadfiledata_dbf_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nyc_coordinates",
            name="x_coord",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="nyc_coordinates",
            name="y_coord",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="dbf_file",
            field=models.FileField(upload_to="Spatial_Files42319"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shp_file",
            field=models.FileField(upload_to="Spatial_Files42319"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shx_file",
            field=models.FileField(upload_to="Spatial_Files42319"),
        ),
    ]
