# Generated by Django 4.2.4 on 2023-08-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_nyc_coordinates_x_coord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nyc_coordinates",
            name="x_coord",
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name="nyc_coordinates",
            name="y_coord",
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="dbf_file",
            field=models.FileField(upload_to="Spatial_Files92854"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shp_file",
            field=models.FileField(upload_to="Spatial_Files92854"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shx_file",
            field=models.FileField(upload_to="Spatial_Files92854"),
        ),
    ]
