# Generated by Django 4.2.4 on 2023-08-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_nyc_coordinates_x_coord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedSQLData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shx_file", models.FileField(upload_to="sql_data")),
                ("is_loaded", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="uploadfiledata",
            name="is_loaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="dbf_file",
            field=models.FileField(upload_to="Spatial_Files90750"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shp_file",
            field=models.FileField(upload_to="Spatial_Files90750"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shx_file",
            field=models.FileField(upload_to="Spatial_Files90750"),
        ),
    ]
