# Generated by Django 4.2.4 on 2023-08-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_uploadedsqldata_uploadfiledata_is_loaded_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedsqldata",
            old_name="shx_file",
            new_name="sql_file",
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="dbf_file",
            field=models.FileField(upload_to="Spatial_Files57210"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shp_file",
            field=models.FileField(upload_to="Spatial_Files57210"),
        ),
        migrations.AlterField(
            model_name="uploadfiledata",
            name="shx_file",
            field=models.FileField(upload_to="Spatial_Files57210"),
        ),
    ]
