# Generated by Django 4.2.4 on 2023-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_shx_file_uploadedsqldata_sql_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiledata',
            name='dbf_file',
            field=models.FileField(upload_to='Spatial_Files68738'),
        ),
        migrations.AlterField(
            model_name='uploadfiledata',
            name='shp_file',
            field=models.FileField(upload_to='Spatial_Files68738'),
        ),
        migrations.AlterField(
            model_name='uploadfiledata',
            name='shx_file',
            field=models.FileField(upload_to='Spatial_Files68738'),
        ),
    ]
