# Generated by Django 3.2.10 on 2023-08-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_uploadfiledata_dbf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiledata',
            name='dbf_file',
            field=models.FileField(upload_to='Spatial_Files85224'),
        ),
        migrations.AlterField(
            model_name='uploadfiledata',
            name='shp_file',
            field=models.FileField(upload_to='Spatial_Files85224'),
        ),
        migrations.AlterField(
            model_name='uploadfiledata',
            name='shx_file',
            field=models.FileField(upload_to='Spatial_Files85224'),
        ),
    ]
