# Generated by Django 3.2.10 on 2023-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20230812_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiledata',
            name='dbf_file',
            field=models.FileField(upload_to='Spatial_Files76934'),
        ),
        migrations.AlterField(
            model_name='uploadfiledata',
            name='shp_file',
            field=models.FileField(upload_to='Spatial_Files76934'),
        ),
        migrations.AlterField(
            model_name='uploadfiledata',
            name='shx_file',
            field=models.FileField(upload_to='Spatial_Files76934'),
        ),
    ]
