# Generated by Django 4.2.4 on 2023-08-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230812_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiledata',
            name='dbf_file',
            field=models.FileField(upload_to='Spatial_Files83650'),
        ),
        migrations.AlterField(
            model_name='uploadfiledata',
            name='shp_file',
            field=models.FileField(upload_to='Spatial_Files83650'),
        ),
        migrations.AlterField(
            model_name='uploadfiledata',
            name='shx_file',
            field=models.FileField(upload_to='Spatial_Files83650'),
        ),
    ]
